from __future__ import annotations

from dataclasses import dataclass


@dataclass
class GroupedMoEIRSpec:
    backend: str
    target: str
    hidden: int
    intermediate: int
    dtype: str
    max_experts: int
    max_assignments: int


def build_grouped_moe_ir(profile: dict) -> GroupedMoEIRSpec:
    """Return a normalized spec used by codegen/tuning.

    This file intentionally does not pretend that a full CUDA/Metal fused MoE TIR
    exists.  The real entry point is generated by tvm_grouped_moe_codegen.py.
    CPU/LLVM codegen emits a working C ABI reference kernel.  GPU targets stay
    unavailable until target-specific TIR/device wrappers are implemented.
    """
    return GroupedMoEIRSpec(
        backend=str(profile.get("backend", "cpu")),
        target=str(profile.get("target", "llvm")),
        hidden=int(profile["hidden"]),
        intermediate=int(profile["intermediate"]),
        dtype=str(profile.get("dtype", "fp32")).lower(),
        max_experts=int(profile.get("max_experts", 8)),
        max_assignments=int(profile.get("max_assignments", 256)),
    )
