#include "glm5_pc_engine.h"

#include "../../system_memory.h"
#include "../native/fp4_decode.h"
#include "../native/glm5_scale4.h"
#include "../../engine_core/kv/kv_qkv.h"
#include "../../engine_core/core/mmap_loader.h"
#include "../../loader/path_join.h"
#include "../../loader/wide_path.h"

#include <algorithm>
#include <atomic>
#include <cerrno>
#include <condition_variable>
#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <deque>
#include <fstream>
#include <functional>
#include <mutex>
#include <memory>
#include <queue>
#include <limits>
#include <sstream>
#include <shared_mutex>
#include <string>
#include <thread>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#else
#include <dlfcn.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
#endif

#include "storage_llm_tools.h"
#include "parts/io_atomic_stats_state.cpp.inc"
#include "parts/engine_types.cpp.inc"
#include "parts/device_types.cpp.inc"
#include "parts/engine_state.cpp.inc"
#include "parts/csv_numbers.cpp.inc"
#include "parts/projection_parse.cpp.inc"
#include "parts/tensor_slots.cpp.inc"
#include "parts/tensor_paths.cpp.inc"
#include "parts/model_root_validate.cpp.inc"
#include "parts/device_cuda_driver.cpp.inc"
#include "parts/tensor_layout.cpp.inc"
#include "parts/residency_helpers.cpp.inc"
#include "parts/residency_usage.cpp.inc"
#include "parts/backend_compiled_flags.cpp.inc"
#include "parts/backend_kernel_flags.cpp.inc"
#include "parts/backend_choose.cpp.inc"
#include "parts/backend_common_cache.cpp.inc"
#include "parts/backend_caps_helpers.cpp.inc"
#include "parts/backend_caps.cpp.inc"
#include "parts/model_library_paths.cpp.inc"
#include "parts/model_library_source.cpp.inc"
#include "parts/model_library_load.cpp.inc"
#include "parts/io_path.cpp.inc"
#include "parts/common_residency.cpp.inc"
#include "parts/staging_alloc.cpp.inc"
#include "parts/prefetch_bytes.cpp.inc"
#include "parts/staging_slots.cpp.inc"
#include "parts/io_stats_helpers.cpp.inc"
#include "parts/device_allocator.cpp.inc"
#include "parts/device_tensor_copy.cpp.inc"
#include "parts/residency_eviction.cpp.inc"
#include "parts/device_raw_copy.cpp.inc"
#include "parts/prefetch_model_bytes.cpp.inc"
#include "parts/prefetch_disk.cpp.inc"
#include "parts/prefetch_pinned.cpp.inc"
#include "parts/prefetch_devices.cpp.inc"
#include "parts/queue_helpers.cpp.inc"
#include "parts/io_worker_loop.cpp.inc"
#include "parts/pinned_worker_loop.cpp.inc"
#include "parts/gpu_worker_loop.cpp.inc"
#include "parts/worker_caps.cpp.inc"
#include "parts/runtime_orchestrator_workers.cpp.inc"
#include "parts/io_worker_lifecycle.cpp.inc"
#include "parts/enqueue_tensor_prefetch.cpp.inc"
#include "parts/default_configs.cpp.inc"
#include "parts/parallel_rows_pool.cpp.inc"
#include "parts/parallel_rows.cpp.inc"
#include "parts/lifecycle_backend_api.cpp.inc"
#include "parts/optimization_plan.cpp.inc"
#include "parts/kv_residency_api.cpp.inc"
#include "parts/residency_stats.cpp.inc"
#include "parts/io_config_api.cpp.inc"
#include "parts/common_raw_prefetch.cpp.inc"
#include "parts/moe_activation_api.cpp.inc"
#include "parts/prefetch_plan_helpers.cpp.inc"
#include "parts/expert_prefetch_api.cpp.inc"
#include "parts/prefetch_plan_topology.cpp.inc"
#include "parts/prefetch_plan.cpp.inc"
#include "parts/prefetch_admission.cpp.inc"
#include "parts/prefetch_plan_execute.cpp.inc"
#include "parts/runtime_orchestrator_items.cpp.inc"
#include "parts/topology_load.cpp.inc"
#include "parts/topology_save.cpp.inc"
#include "parts/topology_record.cpp.inc"
#include "parts/runtime_orchestrator.cpp.inc"
#include "parts/codec_table_columns.cpp.inc"
#include "parts/codec_table.cpp.inc"
#include "parts/tensor_fp16.cpp.inc"
#include "parts/tensor_scale_lookup.cpp.inc"
#include "parts/tensor_query.cpp.inc"
#include "parts/tensor_dot_cpu_kernels.cpp.inc"
#include "parts/tensor_dot.cpp.inc"
#include "parts/raw_forward_cpu.cpp.inc"
#include "parts/generation_api.cpp.inc"
#include "parts/forward_status.cpp.inc"
#include "parts/expert_triplet_cpu.cpp.inc"
#include "parts/token_grouping.cpp.inc"
#include "parts/names_core.cpp.inc"
#include "parts/names_backend.cpp.inc"

